version: "3"

services:
  mkdocs:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: "host"
    environment:
      DISPLAY: localhost:0.0
    container_name: mkdocs
    stdin_open: true
    volumes:
      - ../:/work_dir
    working_dir: /work_dir
